global_costmap:
   global_frame: map
   robot_base_frame: GimbalMiddlePart_1
   update_frequency: 6.0
   publish_frequency: 3.0
   static_map: false
   rolling_window: true
   resolution: 0.01
   transform_tolerance: 1.0
   map_type: costmap