local_costmap:
   global_frame: map
   robot_base_frame: GimbalMiddlePart_1
   update_frequency: 10.0
   publish_frequency: 3.0
   static_map: false
   rolling_window: true
   width: 3.0
   height: 3.0
   resolution: 0.01
   transform_tolerance: 1.0